### ISSUE TITLE
Grunt can't load tasks

### ISSUE THREAD

**Issue by skeenan947** [r1chardj0n3s/angboard#11]
skeenan😎 FireFly:~/dev/angboard$ tox -e grunt -- -d --stack test
grunt installed: Flask==0.10.1,itsdangerous==0.24,Jinja2==2.8,MarkupSafe==0.23,nodeenv==0.13.3,requests==2.7.0,Werkzeug==0.10.4,wheel==0.24.0
grunt runtests: PYTHONHASHSEED='3334899424'
grunt runtests: commands[0] | bash ./bin/nodeenv.sh /Users/skeenan/dev/angboard/.tox/grunt 0.10.29
grunt runtests: commands[1] | npm install
npm WARN package.json angboard@0.0.0 No repository field.
npm WARN package.json angboard@0.0.0 No license field.
grunt runtests: commands[2] | /Users/skeenan/dev/angboard/node_modules/.bin/bower install --config.interactive=false
bower                          no-home HOME not set, user configuration will not be loaded
grunt runtests: commands[3] | /Users/skeenan/dev/angboard/node_modules/.bin/grunt -d --stack test
Loading "Gruntfile.js" tasks...ERROR

> > TypeError: Cannot read property 'prototype' of undefined
> > Warning: Task "test" not found. Use --force to continue.
> > Error: Task "test" not found.
> >     at Task.run (/Users/skeenan/dev/angboard/node_modules/grunt/lib/util/task.js:179:28)
> >     at /Users/skeenan/dev/angboard/node_modules/grunt/lib/grunt.js:161:39
> >     at Array.forEach (native)
> >     at Object.grunt.tasks (/Users/skeenan/dev/angboard/node_modules/grunt/lib/grunt.js:161:9)
> >     at Object.module.exports [as cli](/Users/skeenan/dev/angboard/node_modules/grunt/lib/grunt/cli.js:38:9)
> >     at Object.<anonymous> (/Users/skeenan/dev/angboard/node_modules/grunt-cli/bin/grunt:45:20)
> >     at Module._compile (module.js:460:26)
> >     at Object.Module._extensions..js (module.js:478:10)
> >     at Module.load (module.js:355:32)
> >     at Function.Module._load (module.js:310:12)

Aborted due to warnings.
ERROR: InvocationError: '/Users/skeenan/dev/angboard/node_modules/.bin/grunt -d --stack test'
_________________________________________________________________________________________________________ summary _________________________________________________________________________________________________________
ERROR:   grunt: commands failed

**Comment by skeenan947** [comment]
all tasks are failing.  Gruntfile seems OK though.

**Comment by r1chardj0n3s** [comment]
Hi, this project is abandonded, thanks for your interest though!
